version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: finalizabot-web
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  etl-api:
    build:
      context: .
      dockerfile: apps/etl/Dockerfile
    container_name: finalizabot-etl-api
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      CORS: "true"
      PORT: "4000"
    ports:
      - "4000:4000"
    command: ["node", "dist/api/server.js"]
